import { getLanguage } from "./i18n.js";

const comics = {
  "dust-devourer": {
    page: 1,
    title: "Bus-Stop Dust-Up!",
    titleEs: "¡Lío en la parada!",
    lesson: "Dust high places first, then sweep or vacuum the floor so dust is collected once.",
    lessonEs: "Quita primero el polvo de lugares altos; después barre o aspira el piso.",
    scenes: [
      "At the city bus stop, Dust Devourer gulps grit and sneezes it into giant clouds!",
      "Maya discovers that the cleaner it gets, the smaller the dust cloud becomes.",
      "Leo calls: Dusters high! Bins ready! Work from top to bottom.",
      "Swish! Wipe! The monster's sneeze shrinks to one tiny puff.",
      "Dust Devourer learns that cleaning together feels better than sneezing alone.",
    ],
    scenesEs: [
      "En la parada, el Devorador de Polvo traga tierra y la estornuda en nubes gigantes.",
      "Maya descubre que cuanto más limpio queda, más pequeña se vuelve la nube.",
      "Leo ordena: ¡Plumeros arriba! Limpiemos de arriba hacia abajo.",
      "¡Swish! ¡Limpia! El estornudo se convierte en una nubecita.",
      "El Devorador aprende que limpiar juntos es mejor que estornudar solo.",
    ],
  },
  "sock-stealer": {
    page: 2,
    title: "The Laundromat Mix-Up",
    titleEs: "Revuelto en la lavandería",
    lesson: "Match socks when laundry is dry, then put every pair in the correct drawer.",
    lessonEs: "Empareja los calcetines cuando se sequen y guarda cada par en su cajón.",
    scenes: [
      "Sock Stealer races between the washers, turning every pair into a silly mismatch.",
      "Leo notices it can grab loose socks, but it cannot fool a matched pair.",
      "Maya searches for matching colors and patterns.",
      "Match! Fold! Basket! The sock storm loses its spin.",
      "Sock Stealer becomes the laundromat's official Pair Finder.",
    ],
    scenesEs: [
      "El Ladrón de Calcetines corre entre lavadoras y separa cada par.",
      "Leo descubre que no puede engañar a un par unido.",
      "Maya busca colores y dibujos iguales para formar parejas.",
      "¡Une! ¡Dobla! ¡Guarda! La tormenta pierde fuerza.",
      "El Ladrón se convierte en el buscador oficial de parejas.",
    ],
  },
  "toy-tumbler": {
    page: 3,
    title: "Park Cart Chaos",
    titleEs: "Caos en el parque",
    lesson: "Give every toy a home and put away one category before beginning another.",
    lessonEs: "Dale un hogar a cada juguete. Guarda una categoría antes de empezar otra.",
    scenes: [
      "Toy Tumbler bounces through the park and tips the community toy cart.",
      "Maya realizes it gets bouncier whenever toys have no home.",
      "Leo sorts balls, blocks, colors, and kinds into separate groups.",
      "Roll! Stack! Click! Every toy returns to its own bin.",
      "With nothing left to tumble, the monster helps roll the cart away.",
    ],
    scenesEs: [
      "El Volteador rebota por el parque y vuelca el carrito de juguetes.",
      "Maya descubre que rebota más cuando los juguetes no tienen hogar.",
      "Leo ordena pelotas y bloques por tipo y color.",
      "¡Rueda! ¡Apila! ¡Clic! Cada juguete vuelve a su caja.",
      "Sin nada que voltear, el monstruo ayuda a guardar el carrito.",
    ],
  },
  "book-basher": {
    page: 4,
    title: "Library Book Boom",
    titleEs: "Bum en la biblioteca",
    lesson: "Use a bookmark, close books gently, and return each one to its shelf.",
    lessonEs: "Usa un marcador, cierra los libros con cuidado y devuélvelos a su lugar.",
    scenes: [
      "Book Basher makes library books leap, flap, and land in mixed-up piles.",
      "Leo sees that shelf order and gentle hands make its power fade.",
      "Maya puts bookmarks in, spines out, and books standing tall.",
      "Sort! Slide! Shhh! The flying books settle into place.",
      "Book Basher reforms as a careful shelf helper.",
    ],
    scenesEs: [
      "El Golpeador hace que los libros salten y caigan en montones mezclados.",
      "Leo descubre que el orden y las manos cuidadosas debilitan su poder.",
      "Maya coloca marcadores dentro y libros bien derechos.",
      "¡Ordena! ¡Desliza! ¡Shhh! Los libros voladores se calman.",
      "El monstruo se convierte en un cuidadoso ayudante de estantes.",
    ],
  },
  "crumb-cruncher": {
    page: 5,
    title: "Cafe Crumb Caper",
    titleEs: "Misterio en el café",
    lesson: "Eat over a plate, close food packages, and wipe crumbs after snacks.",
    lessonEs: "Come sobre un plato, cierra los paquetes y limpia las migas después de comer.",
    scenes: [
      "At the plaza cafe, Crumb Cruncher multiplies every cracker crumb it chomps.",
      "Maya discovers it can only multiply crumbs that are left behind.",
      "Leo seals the snacks, wipes the tables, and sweeps under chairs.",
      "Zip! Wipe! Sweep! Even the pigeons cheer for the clean plaza.",
      "Crumb Cruncher accepts a plate and promises to keep its crumbs on it.",
    ],
    scenesEs: [
      "En el café, el Triturador multiplica cada miga de galleta que mastica.",
      "Maya descubre que solo puede multiplicar las migas que quedan tiradas.",
      "Leo cierra las bolsas, limpia las mesas y barre bajo las sillas.",
      "¡Cierra! ¡Limpia! ¡Barre! Hasta las palomas celebran.",
      "El monstruo acepta un plato y promete mantener allí sus migas.",
    ],
  },
  "laundry-lurker": {
    page: 6,
    title: "The Tangled Laundromat",
    titleEs: "Lavandería enredada",
    lesson: "Fold clean clothes while warm and put them away before starting another load.",
    lessonEs: "Dobla la ropa limpia mientras está tibia y guárdala antes de otra carga.",
    scenes: [
      "Laundry Lurker tunnels through clean clothes and tangles sleeves into a giant knot.",
      "Leo learns it hides in heaps, but flat piles leave nowhere to lurk.",
      "Maya shakes, smooths, folds, and sorts each person's clothes.",
      "Flap! Fold! Stack! The laundry mountain becomes neat towers.",
      "Laundry Lurker learns to fold towels into perfect squares.",
    ],
    scenesEs: [
      "El Acechador se esconde en ropa limpia y enreda las mangas en un gran nudo.",
      "Leo aprende que no puede esconderse en pilas planas.",
      "Maya sacude, alisa, dobla y separa la ropa de cada persona.",
      "¡Sacude! ¡Dobla! ¡Apila! La montaña se vuelve ordenada.",
      "El monstruo aprende a doblar toallas en cuadrados perfectos.",
    ],
  },
  "drawer-digger": {
    page: 7,
    title: "Art-Room Drawer Dash",
    titleEs: "Carrera en el salón de arte",
    lesson: "Keep similar supplies together, use labels, and close every drawer after use.",
    lessonEs: "Junta materiales parecidos, usa etiquetas sencillas y cierra cada cajón.",
    scenes: [
      "Drawer Digger opens every art drawer and mixes crayons, brushes, and paper.",
      "Maya sees it digs fastest when supplies are jumbled together.",
      "Leo makes trays by type and picture labels for every supply.",
      "Sort! Snap! Shut! The monster's digging mitts finally slow down.",
      "Drawer Digger becomes the class supply checker.",
    ],
    scenesEs: [
      "El Excavador abre los cajones y mezcla crayones, pinceles y papel.",
      "Maya descubre que excava más rápido cuando todo está revuelto.",
      "Leo crea bandejas por tipo y dibujos que indican dónde va cada cosa.",
      "¡Ordena! ¡Cierra! Sus enormes manos por fin se detienen.",
      "El monstruo se vuelve el encargado de revisar los materiales.",
    ],
  },
  "backpack-burrower": {
    page: 8,
    title: "Hallway Paper Blast",
    titleEs: "Explosión de papeles",
    lesson: "Empty your backpack daily, discard trash, file papers, and restock supplies.",
    lessonEs: "Vacía tu mochila a diario: tira basura, archiva papeles y repón materiales.",
    scenes: [
      "Backpack Burrower nests inside Leo's open bag and blasts papers down the hall.",
      "Leo learns that folders and pouches block the monster's tunnels.",
      "Maya puts papers in the folder, pencils in the case, and lunch in its pocket.",
      "Zip! Clip! Ready! The backpack stands neat and balanced.",
      "The cozy monster accepts a small outside pocket as its tidy travel seat.",
    ],
    scenesEs: [
      "El Cavador anida en la mochila abierta de Leo y lanza papeles por el pasillo.",
      "Leo aprende que las carpetas y los estuches bloquean sus túneles.",
      "Maya guarda papeles, lápices y almuerzo en sus lugares.",
      "¡Zip! ¡Clic! ¡Lista! La mochila queda ordenada y equilibrada.",
      "El monstruo acepta viajar sentado en un pequeño bolsillo exterior.",
    ],
  },
  "wall-doodler": {
    page: 9,
    title: "Community-Center Color Swirl",
    titleEs: "Remolino de color",
    lesson: "Keep art supplies together, draw on paper, and clean stray marks promptly.",
    lessonEs: "Guarda crayones y marcadores juntos. Dibuja en papel y limpia marcas pronto.",
    scenes: [
      "Wall Doodler's glowing tail covers the community center with looping marks.",
      "Maya notices its tail follows any big blank space.",
      "Leo gives its creativity the right home on approved paper.",
      "Spray! Wipe! Tape! A huge washable paper mural goes up.",
      "Wall Doodler joins the heroes and creates an approved masterpiece.",
    ],
    scenesEs: [
      "La cola brillante del Garabateador cubre el centro comunitario de líneas.",
      "Maya descubre que su cola sigue cualquier espacio grande y vacío.",
      "Leo da a su creatividad un buen hogar sobre papel aprobado.",
      "¡Rocía! ¡Limpia! ¡Pega! Colocan un mural enorme de papel lavable.",
      "El monstruo se une a los héroes y crea una obra aprobada.",
    ],
  },
  "nighttime-ninja": {
    page: 10,
    title: "The Midnight Kitchen Mission",
    titleEs: "Misión en la cocina",
    lesson: "Before bed, return items, close doors, wipe surfaces, and check the floor.",
    lessonEs: "Antes de dormir: guarda, cierra, limpia y revisa el piso.",
    scenes: [
      "Nighttime Ninja silently leaves cabinets open and snack supplies everywhere.",
      "Leo discovers that a checklist reveals every moonlit clue.",
      "Maya calls the quiet sequence: close, return, wipe, check.",
      "Click! Swish! Done! The kitchen is reset before sunrise.",
      "Nighttime Ninja becomes the family's silent final checker.",
    ],
    scenesEs: [
      "El Ninja Nocturno deja gabinetes abiertos y bocadillos por todas partes.",
      "Leo descubre que una lista revela todas las pistas bajo la luna.",
      "Maya indica la secuencia: cierra, devuelve, limpia y revisa.",
      "¡Clic! ¡Swish! ¡Listo! La cocina queda limpia antes del amanecer.",
      "El Ninja se convierte en el revisor silencioso de la familia.",
    ],
  },
};

export function comicStory(monsterId) {
  const story = comics[monsterId];
  if (!story) return null;
  const spanish = getLanguage() === "es";
  return {
    ...story,
    title: spanish ? story.titleEs : story.title,
    scenes: spanish ? story.scenesEs : story.scenes,
    lesson: spanish ? story.lessonEs : story.lesson,
    image: `./assets/comics/${spanish ? "es" : "en"}/page-${String(story.page).padStart(2, "0")}.jpg`,
  };
}
